### ISSUE TITLE
Forgetting to free the allocated memory can cause memory leak

### ISSUE THREAD

**Issue by Zero0one1** [JayFoxRox/lirc-xboxlibusb#3]
According to the [ALSA library document](https://www.alsa-project.org/alsa-doc/alsa-lib/group___control.html#ga8546500ca828392f03f5bba2e7813874), we should free the return value of `snd_device_name_get_hint()` after use. Otherwise, it will cause the memory leak. `name` in L547 and `desc` in L549 can be simply freed using `free()`.

https://github.com/JayFoxRox/lirc-xboxlibusb/blob/67a8cc4288e58c124c4b32e50ef41d2d85992623/plugins/audio_alsa.c#L530-L556

**Comment by JayFoxRox** [comment]
The only commit that should be discussed on this issue tracker is https://github.com/JayFoxRox/lirc-xboxlibusb/commit/67a8cc4288e58c124c4b32e50ef41d2d85992623

Please report any other issue with upstream LIRC: https://lirc.org/.

Closing.
